name: Fetch Online Data

on:
  schedule:
    - cron: '*/10 * * * *'  # каждые 10 минут
  workflow_dispatch:

jobs:
  fetch_online:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install

      - name: Install dependencies for Puppeteer
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl libxss1 libappindicator3-1 libindicator7

      - name: Fetch Online Data
        run: |
          echo 'const puppeteer = require("puppeteer");' > fetchOnline.js
          echo 'const puppeteer = require("puppeteer");' >> fetchOnline.js
          echo 'async function fetchOnline() {' >> fetchOnline.js
          echo '  const browser = await puppeteer.launch({ args: ["--no-sandbox", "--disable-setuid-sandbox"] });' >> fetchOnline.js
          echo '  const page = await browser.newPage();' >> fetchOnline.js
          echo '  await page.goto("https://www.customgamestats.com/games/2880603428", {waitUntil: "domcontentloaded"});' >> fetchOnline.js
          echo '  const online = await page.$eval(".stat-value", el => el.innerText);' >> fetchOnline.js
          echo '  const updatedAt = new Date().toISOString();' >> fetchOnline.js
          echo '  console.log(JSON.stringify({ now_players: online, updated_at: updatedAt }));' >> fetchOnline.js
          echo '  await browser.close();' >> fetchOnline.js
          node fetchOnline.js > data.json
