name: Update Online JSON

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch HTML and parse online count
        run: |
          # Загружаем HTML
          curl -s -H "User-Agent: Mozilla/5.0" https://www.customgamestats.com/games/2880603428 -o page.html

          # Ищем строку с "Current Players"
          ONLINE=$(grep -oP 'Current Players\s*</div>\s*<div class="stat-value">\K\d+' page.html)

          # Записываем в JSON
          echo "{ \"now_players\": $ONLINE, \"updated_at\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\" }" > data.json

      - name: Commit and Push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add data.json
          git commit -m "Update data" || echo "No changes"
          git push
