name: Update Leaderboard

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Generate Rating leaderboard
        run: php generate_leaderboard.php
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
      - name: Generate Arena leaderboard
        run: php generate_arena_leaderboard.php
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
      - name: Show debug log
        run: cat arena_debug.log || echo "Debug log not found"
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add leaderboard.json arena_leaderboard.json arena_debug.log
          git commit -m "Update leaderboards with debug log" || echo "No changes to commit"
          git push
